### ISSUE TITLE
Run JmavSim in HITL Mode

### ISSUE THREAD

**Issue by anujkumargupta** [PX4/jMAVSim#35] opened 2016-09-22 13:31 UTC
I am trying to run Jmavsim in HITL mode. I follwed the link
https://pixhawk.org/dev/hil/jmavsim
and used /dev/ttyACM0(Pixhawk connected through usb(serial)) and /dev/ttyUSB0(Pixhawk connected through radio telemetry(udp)) and as mention in link ttyusbmodem1 but every time it throws serial port exception either port not found or port busy.

Thanks.

**Comment by dagar** [comment] 2016-09-22 15:13
Is QGroundControl running?

**Comment by anujkumargupta** [comment] 2016-09-22 19:27
Yes its running. I followed the same instructions as mentioned in link in my last comment.

**Comment by dagar** [comment] 2016-09-22 19:50
It's probably QGroundControl autoconnecting first. Kill QGroundControl, start jmavsim, then start QGC (if needed).

**Comment by anujkumargupta** [comment] 2016-09-23 05:05
Thanks , Now it does not throw that error but its not showing any mavlink messages in terminal. Even its not showing the init mavlink.

**Comment by dagar** [comment] 2016-09-23 12:23
What do you get?

![screenshot from 2016-09-23 08-18-35](https://cloud.githubusercontent.com/assets/84712/18785467/5cdf6ad4-8166-11e6-92a3-f8427923bb0b.png)

**Comment by anujkumargupta** [comment] 2016-09-23 12:37
I got this.
![screenshot from 2016-09-23 18 06 19](https://cloud.githubusercontent.com/assets/22234294/18785874/856b8436-81b8-11e6-9bbd-bd670d3a390e.png)

**Comment by dagar** [comment] 2016-09-23 12:40
I don't think I quite follow how you've connected with /dev/ttyUSB0 and the telemetry radio.

Can you try with only the usb connection? /dev/ttyACM0

**Comment by anujkumargupta** [comment] 2016-10-19 11:26
Hi , I am trying to do hitl simulation using the snapdragon flight using the command 
java -Djava.ext.dirs= -cp lib/*:out/production/jmavsim.jar me.drton.jmavsim.Simulator -serial /dev/ttyUSB0 921600 -qgc 
but facing problem , jmavsim is starging but i didnot get any mavlink msg
Do i need to change anything in my command( i am confused about 921600)
Thanks

**Comment by salim616** [comment] 2017-02-17 16:01
@DrTon  I have tuned my quad on JmavSim and works very weel on Simulation. the problem is when i write the PID parameters on Pixhwak to test flight . the quad behaves weirdly please find the link for the video : https://www.dropbox.com/s/chxxrwyg2n9kuug/video-1487278360.mp4?dl=0

**Comment by julianoes** [comment] 2018-09-13 13:02
This seems outdated, closing.

**Closed by julianoes** 2018-09-13 13:02 UTC
